# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160407_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
