# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20160410_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=None),
        ),
    ]
