# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='CatalogItem',
            new_name='CatalogProduct',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RenameField(
            model_name='catalogproduct',
            old_name='item',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, 'Корзина'), (2, 'На обработке'), (3, 'Отправлен'), (4, 'Отменен'), (5, 'Завершен')], default=1),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='backend.OrderProduct', to='backend.Product'),
        ),
    ]
