# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20160411_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogproduct',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='catalogproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Catalog'),
        ),
        migrations.DeleteModel(
            name='CatalogProduct',
        ),
    ]
