# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20160412_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='alias',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.Catalog'),
        ),
    ]
