# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20160412_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products',
            new_name='tags',
        ),
    ]
